//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintLoc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintLoc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover your account.
        /// </summary>
        internal static string AccountRecoveryEmailSubject {
            get {
                return ResourceManager.GetString("AccountRecoveryEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintLoc.View.ConfirmationCodeControl.
        /// </summary>
        internal static string ConfirmationCodeControlPath {
            get {
                return ResourceManager.GetString("ConfirmationCodeControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Code.
        /// </summary>
        internal static string ConfirmationCodeWindowTitle {
            get {
                return ResourceManager.GetString("ConfirmationCodeWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintLoc.View.ForgotPasswordControl.
        /// </summary>
        internal static string ForgotPasswordControlPath {
            get {
                return ResourceManager.GetString("ForgotPasswordControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPassword.
        /// </summary>
        internal static string ForgotPasswordWindowTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received a request to confirm your account. Your account confirmation code is: .
        /// </summary>
        internal static string GenericEmailContent {
            get {
                return ResourceManager.GetString("GenericEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintLoc.View.HomepageControl.
        /// </summary>
        internal static string HomepageControlPath {
            get {
                return ResourceManager.GetString("HomepageControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage PrintLoc.
        /// </summary>
        internal static string HomepageWindowTitle {
            get {
                return ResourceManager.GetString("HomepageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintLoc.View.LoginControl.
        /// </summary>
        internal static string LoginControlPath {
            get {
                return ResourceManager.GetString("LoginControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintLoc.View.PrinterList.
        /// </summary>
        internal static string PrinterListControlPath {
            get {
                return ResourceManager.GetString("PrinterListControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer List.
        /// </summary>
        internal static string PrinterListWindowTitle {
            get {
                return ResourceManager.GetString("PrinterListWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintLoc.View.PrintJob.
        /// </summary>
        internal static string PrintJobControlPath {
            get {
                return ResourceManager.GetString("PrintJobControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Job.
        /// </summary>
        internal static string PrintJobWindowTitle {
            get {
                return ResourceManager.GetString("PrintJobWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintLoc.View.RegisterControl.
        /// </summary>
        internal static string RegisterAccountControlPath {
            get {
                return ResourceManager.GetString("RegisterAccountControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your account.
        /// </summary>
        internal static string RegisterAccountEmailSubject {
            get {
                return ResourceManager.GetString("RegisterAccountEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Account.
        /// </summary>
        internal static string RegisterAccountWindowTitle {
            get {
                return ResourceManager.GetString("RegisterAccountWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintLoc.View.Report.
        /// </summary>
        internal static string ReportsControlPath {
            get {
                return ResourceManager.GetString("ReportsControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportsWindowTitle {
            get {
                return ResourceManager.GetString("ReportsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintLoc.View.ResetPasswordControl.
        /// </summary>
        internal static string ResetPasswordControlPath {
            get {
                return ResourceManager.GetString("ResetPasswordControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPasswordWindowTitle {
            get {
                return ResourceManager.GetString("ResetPasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\TxtFile\text.txt.
        /// </summary>
        internal static string TextPath {
            get {
                return ResourceManager.GetString("TextPath", resourceCulture);
            }
        }
    }
}
